# Generated by Django 2.2.1 on 2019-05-23 17:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangautoapi', '0002_auto_20190523_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='production_year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2019)]),
        ),
    ]
