# Generated by Django 2.2.1 on 2019-06-05 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangautoapi', '0003_auto_20190523_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModelImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangautoapi.CarModel')),
            ],
        ),
    ]
