# Generated by Django 2.2.1 on 2019-06-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangautoapi', '0004_carmodelimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='stock',
        ),
        migrations.AddField(
            model_name='car',
            name='occassion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
