# Generated by Django 2.2.1 on 2019-06-09 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangautoapi', '0005_auto_20190609_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='occassion',
            new_name='occasion',
        ),
    ]
