# Generated by Django 2.2.1 on 2019-05-23 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangautoapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='creation_date',
            new_name='production_year',
        ),
    ]
